/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticipantsAliasRouteImport } from './routes/participants/$alias'
import { Route as AdminScoresRouteImport } from './routes/admin/scores'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminMatchesRouteImport } from './routes/admin/matches'

const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsAliasRoute = ParticipantsAliasRouteImport.update({
  id: '/participants/$alias',
  path: '/participants/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScoresRoute = AdminScoresRouteImport.update({
  id: '/admin/scores',
  path: '/admin/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/admin/matches',
  path: '/admin/matches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/register': typeof RegisterRoute
  '/stages': typeof StagesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scores': typeof AdminScoresRoute
  '/participants/$alias': typeof ParticipantsAliasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/register': typeof RegisterRoute
  '/stages': typeof StagesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scores': typeof AdminScoresRoute
  '/participants/$alias': typeof ParticipantsAliasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/register': typeof RegisterRoute
  '/stages': typeof StagesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scores': typeof AdminScoresRoute
  '/participants/$alias': typeof ParticipantsAliasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/predictions'
    | '/register'
    | '/stages'
    | '/admin/matches'
    | '/admin/registrations'
    | '/admin/scores'
    | '/participants/$alias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/predictions'
    | '/register'
    | '/stages'
    | '/admin/matches'
    | '/admin/registrations'
    | '/admin/scores'
    | '/participants/$alias'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/login'
    | '/predictions'
    | '/register'
    | '/stages'
    | '/admin/matches'
    | '/admin/registrations'
    | '/admin/scores'
    | '/participants/$alias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PredictionsRoute: typeof PredictionsRoute
  RegisterRoute: typeof RegisterRoute
  StagesRoute: typeof StagesRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminScoresRoute: typeof AdminScoresRoute
  ParticipantsAliasRoute: typeof ParticipantsAliasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/$alias': {
      id: '/participants/$alias'
      path: '/participants/$alias'
      fullPath: '/participants/$alias'
      preLoaderRoute: typeof ParticipantsAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scores': {
      id: '/admin/scores'
      path: '/admin/scores'
      fullPath: '/admin/scores'
      preLoaderRoute: typeof AdminScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/admin/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PredictionsRoute: PredictionsRoute,
  RegisterRoute: RegisterRoute,
  StagesRoute: StagesRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminScoresRoute: AdminScoresRoute,
  ParticipantsAliasRoute: ParticipantsAliasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
